### PR TITLE
init pnp_template check_ms_win_disk_load.php version 2016022601

### PR DESCRIPTION
**Pull request by vinogradovia**
i'm created PNP template for plugin. If you want, you can add this for self.

### CODE REVIEW

**Comment by willemdh** [comment]
Can you show me a screenshot? Im not using pnp4nagios, but im curious whats the result.

**Comment by vinogradovia** [comment]
check_ms_win_disk_load pnp

**Comment by vinogradovia** [comment]
What was used to create a screenshot from a readme page?

**Comment by willemdh** [comment]
Highcharts.

**Pull request merged**
